/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.banco;

import com.mycompany.banco.managerfile.ReadFile;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author DELL
 */
public class Menu extends javax.swing.JFrame{
    
   Banco banco = new Banco();  
    
    
            
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mostrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        solicitarTurno = new javax.swing.JButton();
        atenderPreferencial = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        personaPreferencial = new javax.swing.JTextField();
        personaNoPreferencial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        siguientePreferencial = new javax.swing.JTextField();
        siguienteNoPreferencial = new javax.swing.JTextField();
        atenderNoPreferencial = new javax.swing.JButton();
        consultarTurno = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        colaConPrioridad = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ColaSinPrioridad = new javax.swing.JTextArea();
        consultarCola = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mostrar.setText("Mostrar");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("BANCO");

        solicitarTurno.setText("Solicitar Turno");
        solicitarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarTurnoActionPerformed(evt);
            }
        });

        atenderPreferencial.setText("Atender Preferencial");
        atenderPreferencial.setEnabled(false);
        atenderPreferencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atenderPreferencialActionPerformed(evt);
            }
        });

        jLabel2.setText("COLA PREFERENCIAL");

        jLabel3.setText("COLA NO PREFENCIAL");

        jLabel4.setText("Turno Atendiendo");

        personaPreferencial.setText("Sin Atender");
        personaPreferencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personaPreferencialActionPerformed(evt);
            }
        });

        personaNoPreferencial.setText("Sin Atender");

        jLabel5.setText("Turno Siguiente");

        siguientePreferencial.setText("Sin establecer");

        siguienteNoPreferencial.setText("Sin establecer");

        atenderNoPreferencial.setText("Atender No Preferencial");
        atenderNoPreferencial.setEnabled(false);
        atenderNoPreferencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atenderNoPreferencialActionPerformed(evt);
            }
        });

        consultarTurno.setText("Consultar Turno");
        consultarTurno.setEnabled(false);
        consultarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarTurnoActionPerformed(evt);
            }
        });

        jLabel6.setText("Cola Con Prioridad");
        jLabel6.setEnabled(false);

        jLabel7.setText("Cola Sin Prioridad");
        jLabel7.setEnabled(false);

        colaConPrioridad.setColumns(20);
        colaConPrioridad.setRows(5);
        colaConPrioridad.setEnabled(false);
        jScrollPane1.setViewportView(colaConPrioridad);

        ColaSinPrioridad.setColumns(20);
        ColaSinPrioridad.setRows(5);
        ColaSinPrioridad.setEnabled(false);
        jScrollPane3.setViewportView(ColaSinPrioridad);

        consultarCola.setText("Consultar Colas");
        consultarCola.setEnabled(false);
        consultarCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarColaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(atenderPreferencial)
                                        .addGap(41, 41, 41)
                                        .addComponent(atenderNoPreferencial))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(consultarTurno)
                                            .addComponent(jLabel6))
                                        .addGap(67, 67, 67)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(consultarCola)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addGap(44, 44, 44)))))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(solicitarTurno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(personaPreferencial, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(personaNoPreferencial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(siguienteNoPreferencial, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(siguientePreferencial, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(443, 443, 443)
                                .addComponent(mostrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(solicitarTurno, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(personaPreferencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addComponent(siguientePreferencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(personaNoPreferencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(siguienteNoPreferencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atenderPreferencial)
                            .addComponent(atenderNoPreferencial))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(consultarTurno)
                            .addComponent(consultarCola))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mostrar)
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        String[] nombreColumnas = {"id","tipo de cliente","nombre","correo","telefono","saldo"};
               
        table.setModel(new javax.swing.table.DefaultTableModel(banco.retornarMatriz(), nombreColumnas));
    }//GEN-LAST:event_mostrarActionPerformed

    private void solicitarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarTurnoActionPerformed
        boolean[] habilitar = banco.solicitarTurno();
        if(habilitar[0]==true||habilitar[1]==true){
            consultarTurno.setEnabled(true);
            consultarCola.setEnabled(true);
            colaConPrioridad.setEnabled(true);
            ColaSinPrioridad.setEnabled(true);
        }
        atenderPreferencial.setEnabled(habilitar[0]);
        atenderNoPreferencial.setEnabled(habilitar[1]);
    }//GEN-LAST:event_solicitarTurnoActionPerformed

    private void personaPreferencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personaPreferencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personaPreferencialActionPerformed

    private void atenderPreferencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atenderPreferencialActionPerformed

        personaPreferencial.setText(banco.turno());
        siguientePreferencial.setText(banco.siguienteTurno1());
    }//GEN-LAST:event_atenderPreferencialActionPerformed

    private void atenderNoPreferencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atenderNoPreferencialActionPerformed
        personaNoPreferencial.setText(banco.atenderNoPreferencial());
        siguienteNoPreferencial.setText(banco.siguienteTurno2());
    }//GEN-LAST:event_atenderNoPreferencialActionPerformed

    private void consultarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarTurnoActionPerformed
        banco.consultarTurno();
    }//GEN-LAST:event_consultarTurnoActionPerformed

    private void consultarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarColaActionPerformed
        String[] cola =  banco.consultarCola();
        colaConPrioridad.setText(cola[0]);
        ColaSinPrioridad.setText(cola[1]);
    }//GEN-LAST:event_consultarColaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ColaSinPrioridad;
    private javax.swing.JButton atenderNoPreferencial;
    private javax.swing.JButton atenderPreferencial;
    private javax.swing.JTextArea colaConPrioridad;
    private javax.swing.JButton consultarCola;
    private javax.swing.JButton consultarTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton mostrar;
    private javax.swing.JTextField personaNoPreferencial;
    private javax.swing.JTextField personaPreferencial;
    private javax.swing.JTextField siguienteNoPreferencial;
    private javax.swing.JTextField siguientePreferencial;
    private javax.swing.JButton solicitarTurno;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
